#!/usr/bin/env python2.7

from sys import argv, exit
import argparse
from cs.starter import Starter
from cs.plugins import *
import cs.messages
import cs.configuration as configuration
import cs.debug as debug


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='DCQC - code quality')
    parser.add_argument('branch', help='The branch that have to be checked')
    parser.add_argument('-p', '--path', help='The path of configurations and tests files')
    parser.add_argument('-r', '--result', help='The server result URL')
    parser.add_argument('-s', '--save', help='Path where to save the result locally')
    parser.add_argument('-m', '--master', help='The default master branch')
    parser.add_argument('-d', '--debug', help='Active debug mode', action='store_true')
    parser.add_argument('-o', '--only', help='Process CS only on master branch', action='store_true')

    args = parser.parse_args()

    configuration.setConfig(args)

    cs.messages.header()

    starter = Starter()
    starter.attach(phpcs.Phpcs(starter.control_version, starter.changed_files))
    starter.attach(phpmd.Phpmd(starter.control_version, starter.changed_files))
    starter.attach(phpunitcoverage.Phpunitcoverage(starter.control_version))

    final_status = starter.run()
    debug.show("DCQC RESULT: %s" % (final_status))

    if (final_status == 'bad'):
        exit(1)

